<a href="https://colab.research.google.com/github/TungSoPon/BasicProg_DataViz65/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [203]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [204]:
import os
os.chdir('/content/gdrive/MyDrive/Project_BPDV')

!pwd

/content/gdrive/MyDrive/Project_BPDV

In [205]:
!ls

opendata_project_C.csv	opendata_train_station_C.csv  opendata_unittype_C.csv
opendata_project.csv	opendata_train_station.csv    opendata_unittype.csv

##นำข้อมูลเข้า

In [206]:
import pandas as pd

In [207]:
opendata_project = pd.read_csv('opendata_project.csv')
print(opendata_project.shape)
opendata_project

(23434, 45)

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",...,NaN,1.0,1.0,NaN,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",...,NaN,NaN,NaN,NaN,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",...,NaN,1.0,1.0,NaN,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [208]:
opendata_unittype = pd.read_csv('opendata_unittype.csv')
print(opendata_unittype.shape) 
opendata_unittype

(42625, 27)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42620,37109,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,NaN,157.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,NaN,133.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [209]:
opendata_train_station = pd.read_csv('opendata_train_station.csv')
print(opendata_train_station.shape) 
opendata_train_station

(318, 20)

,row_number,gid,line_no,railway,line_typt,line_type,status,line_th,line_en,station_th,station_en,latitude,longitude,prov_namt,prov_name,amp_namt,amp_name,tam_namt,tam_name,day
0,286,254,9,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,อนาคต,สายสีเหลือง,Yellow Line,ศรีแบริ่ง,Si Bearing,13.644190,100.636665,สมุทรปราการ,SAMUT PRAKAN,บางพลี,BANG PHLI,บางแก้ว,BANG KAEO,30/9/2022
1,265,130,4,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีม่วง,Purple Line,ตลาดบางใหญ่,Talad Bang Yai,13.881849,100.409349,นนทบุรี,NONTHABURI,บางบัวทอง,BANG BUA THONG,บางรักพัฒนา,BANG RAK PHATTHANA,30/9/2022
2,18,110,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,บางแค,Bang Khae,13.711927,100.421581,กรุงเทพมหานคร,BANGKOK,บางแค,BANG KHAE,บางแค,BANG KHAE,30/9/2022
3,263,293,12,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสีเทา,Grey Line,ลาดพร้าว-87,Lat Phrao 87,13.801127,100.614995,กรุงเทพมหานคร,BANGKOK,บางกะปิ,BANG KAPI,คลองจั่น,KHLONG CHAN,30/9/2022
4,235,105,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,วัดมังกร,Wat Mangkon,13.741677,100.510687,กรุงเทพมหานคร,BANGKOK,สัมพันธวงศ์,SAMPHANTHAWONG,สัมพันธวงศ์,SAMPHANTHAWONG,30/9/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,216,286,11,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสีทอง,Gold line,สถานีคลองสาน,Khlong San,13.730545,100.507354,กรุงเทพมหานคร,BANGKOK,คลองสาน,KHLONG SAN,คลองสาน,KHLONG SAN,30/9/2022
314,141,99,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,สามย่าน,Sam Yan,13.732554,100.529493,กรุงเทพมหานคร,BANGKOK,ปทุมวัน,PATHUM WAN,วังใหม่,WANG MAI,30/9/2022
315,131,283,10,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,ปัจจุบัน,สายสีชมพู,Pink Line,ชลประทาน,Royal Irrigation Department,13.898695,100.507030,นนทบุรี,NONTHABURI,ปากเกร็ด,PAK KRET,บางตลาด,BANG TALAT,30/9/2022
316,196,252,9,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,อนาคต,สายสีเหลือง,Yellow Line,ศรีเอี่ยม,Si Iam,13.664307,100.644072,กรุงเทพมหานคร,BANGKOK,บางนา,BANG NA,บางนาใต้,BANG NA TAI,30/9/2022
317,253,32,1,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสุขุมวิท,Sukhumvit Line,อโศก,Asok,13.737045,100.560344,กรุงเทพมหานคร,BANGKOK,คลองเตย,KHLONG TOEI,คลองเตย,KHLONG TOEI,30/9/2022

##Data Clean Project

In [210]:
opendata_project.columns

Index(['row_number', 'project_id', 'name_en', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'price_min',
       'developer_id', 'developer_name_en', 'developer_name_th', 'latitude',
       'longitude', 'neighborhood_id', 'neighborhood_name_en',
       'neighborhood_name_th', 'subdistrict_id', 'subdistrict_name_en',
       'subdistrict_name_th', 'district_id', 'district_name_en',
       'district_name_th', 'province_id', 'province_name_en',
       'province_name_th', 'zipcode', 'count_elevator',
       'count_elevator_service', 'count_floor', 'count_parking', 'count_tower',
       'count_unit', 'count_unittype', 'facility_clubhouse',
       'facility_fitness', 'facility_meeting', 'facility_park',
       'facility_playground', 'facility_pool', 'facility_security',
       'date_created', 'date_finish', 'date_updated', 'source', 'url_project'],
      dtype='object')

In [211]:
opendata_project = opendata_project[['project_id', 'name_en', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'price_min',
       'developer_id', 'developer_name_en', 'developer_name_th', 'latitude',
       'longitude', 'neighborhood_id', 'neighborhood_name_en',
       'neighborhood_name_th', 'subdistrict_id', 'subdistrict_name_en',
       'subdistrict_name_th', 'district_id', 'district_name_en',
       'district_name_th', 'province_id', 'province_name_en',
       'province_name_th', 'zipcode', 'count_elevator',
       'count_elevator_service', 'count_floor', 'count_parking', 'count_tower',
       'count_unit', 'count_unittype', 'facility_clubhouse',
       'facility_fitness', 'facility_meeting', 'facility_park',
       'facility_playground', 'facility_pool', 'facility_security',
       'date_created', 'date_finish', 'date_updated', 'source', 'url_project']]

In [212]:
opendata_project

,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,developer_name_th,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",บริษัท วินนิ่ง แอสเซท พลัส จำกัด,...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",บริษัท กิฟท์ แอสเสท แลนด์ จำกัด,...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",บริษัท พฤกษา เรียลเอสเตท จำกัด (มหาชน),...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",บริษัท เอพี (ไทยแลนด์) จำกัด (มหาชน),...,NaN,1.0,1.0,NaN,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",บริษัท อารียา พรอพเพอร์ตี้ จำกัด (มหาชน),...,NaN,NaN,NaN,NaN,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",บริษัท วังทองกรุ๊ป จำกัด (มหาชน),...,NaN,1.0,1.0,NaN,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",บริษัท โฮมแลนด์ เซอร์วิส จำกัด,...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

Missing/Null Checking Project

In [213]:
opendata_project.dtypes

project_id                 object
name_en                    object
name_th                    object
propertytype_id            object
propertytype_name_en       object
propertytype_name_th       object
price_min                  object
developer_id               object
developer_name_en          object
developer_name_th          object
latitude                  float64
longitude                 float64
neighborhood_id            object
neighborhood_name_en       object
neighborhood_name_th       object
subdistrict_id            float64
subdistrict_name_en        object
subdistrict_name_th        object
district_id               float64
district_name_en           object
district_name_th           object
province_id               float64
province_name_en           object
province_name_th           object
zipcode                   float64
count_elevator             object
count_elevator_service     object
count_floor                object
count_parking              object
count_tower                object
count_unit                float64
count_unittype            float64
facility_clubhouse        float64
facility_fitness          float64
facility_meeting          float64
facility_park             float64
facility_playground       float64
facility_pool             float64
facility_security         float64
date_created               object
date_finish                object
date_updated               object
source                     object
url_project                object
dtype: object

In [214]:
print(len(opendata_project[opendata_project['zipcode'].isnull()])) 
opendata_project = opendata_project.dropna(subset=['zipcode'])

31

In [215]:
print(len(opendata_project[opendata_project['subdistrict_id'].isnull()])) 
opendata_project = opendata_project.dropna(subset=['subdistrict_id'])

10

In [216]:
opendata_project = opendata_project.dropna(subset=['name_en','propertytype_name_en','price_min','name_th','propertytype_name_th'])

In [217]:
opendata_project['developer_name_en'] = opendata_project['developer_name_en'].fillna('Unknown')
opendata_project['developer_name_th'] = opendata_project['developer_name_th'].fillna('Unknown')
opendata_project['neighborhood_id'] = opendata_project['neighborhood_id'].fillna('Unknown') 
opendata_project['neighborhood_name_en'] = opendata_project['neighborhood_name_en'].fillna('Unknown')
opendata_project['neighborhood_name_th'] = opendata_project['neighborhood_name_th'].fillna('Unknown')
opendata_project['date_finish'] = opendata_project['date_finish'].fillna('Unknown')

In [218]:
opendata_project[['count_floor', 'count_unit','count_unittype']]  = opendata_project[['count_floor', 'count_unit','count_unittype']].fillna(1)
opendata_project[['count_elevator','count_floor','count_parking', 'count_elevator_service','count_tower']] = opendata_project[['count_elevator','count_floor','count_parking', 'count_elevator_service','count_tower']].fillna(0) 
# สิ่งอำนวยความสะดวก
opendata_project[['facility_clubhouse','facility_fitness','facility_meeting','facility_park','facility_playground','facility_pool','facility_security']] = opendata_project[['facility_clubhouse','facility_fitness','facility_meeting','facility_park','facility_playground','facility_pool','facility_security']].fillna(0)

In [219]:
opendata_project.isnull().any()

project_id                False
name_en                   False
name_th                   False
propertytype_id           False
propertytype_name_en      False
propertytype_name_th      False
price_min                 False
developer_id              False
developer_name_en         False
developer_name_th         False
latitude                  False
longitude                 False
neighborhood_id           False
neighborhood_name_en      False
neighborhood_name_th      False
subdistrict_id            False
subdistrict_name_en       False
subdistrict_name_th       False
district_id               False
district_name_en          False
district_name_th          False
province_id               False
province_name_en          False
province_name_th          False
zipcode                   False
count_elevator            False
count_elevator_service    False
count_floor               False
count_parking             False
count_tower               False
count_unit                False
count_unittype            False
facility_clubhouse        False
facility_fitness          False
facility_meeting          False
facility_park             False
facility_playground       False
facility_pool             False
facility_security         False
date_created              False
date_finish               False
date_updated              False
source                    False
url_project               False
dtype: bool

In [220]:
opendata_project

,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,developer_name_th,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",บริษัท วินนิ่ง แอสเซท พลัส จำกัด,...,0.0,0.0,0.0,1.0,1.0,2020-06-10 14:36:04,Unknown,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",บริษัท กิฟท์ แอสเสท แลนด์ จำกัด,...,0.0,1.0,0.0,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,Unknown,Unknown,...,0.0,0.0,0.0,0.0,0.0,2022-05-05 16:43:28,Unknown,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,Unknown,Unknown,...,0.0,0.0,0.0,0.0,0.0,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",บริษัท พฤกษา เรียลเอสเตท จำกัด (มหาชน),...,0.0,1.0,0.0,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",บริษัท เอพี (ไทยแลนด์) จำกัด (มหาชน),...,0.0,1.0,1.0,0.0,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",บริษัท อารียา พรอพเพอร์ตี้ จำกัด (มหาชน),...,0.0,0.0,0.0,0.0,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",บริษัท วังทองกรุ๊ป จำกัด (มหาชน),...,0.0,1.0,1.0,0.0,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",บริษัท โฮมแลนด์ เซอร์วิส จำกัด,...,0.0,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,Unknown,Unknown,...,0.0,0.0,0.0,0.0,0.0,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [221]:
opendata_project.to_csv('opendata_project_C.csv', index=False)

##Data Clean Unittype

In [222]:
opendata_unittype.columns

Index(['row_number', 'unittype_id', 'project_id', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'area_total_min_wa',
       'area_usable_min', 'price_min', 'count_airconditioner',
       'count_elevator', 'count_floor_internal', 'count_parking',
       'count_room_bath', 'count_room_bed', 'count_room_dinning',
       'count_room_guest', 'count_room_kitchen', 'count_room_living',
       'count_room_maid', 'count_room_storage', 'count_room_utility',
       'date_created', 'date_updated', 'source', 'url_unittype'],
      dtype='object')

In [223]:
opendata_unittype = opendata_unittype[['unittype_id', 'project_id', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'area_total_min_wa',
       'area_usable_min', 'price_min', 'count_airconditioner',
       'count_elevator', 'count_floor_internal', 'count_parking',
       'count_room_bath', 'count_room_bed', 'count_room_dinning',
       'count_room_guest', 'count_room_kitchen', 'count_room_living',
       'count_room_maid', 'count_room_storage', 'count_room_utility',
       'date_created', 'date_updated', 'source', 'url_unittype']]
opendata_unittype

,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,count_airconditioner,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,NaN,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42620,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,NaN,157.0,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,NaN,133.0,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [224]:
opendata_unittype.dtypes

unittype_id              object
project_id               object
name_th                  object
propertytype_id           int64
propertytype_name_en     object
propertytype_name_th     object
area_total_min_wa       float64
area_usable_min         float64
price_min               float64
count_airconditioner    float64
count_elevator          float64
count_floor_internal    float64
count_parking           float64
count_room_bath         float64
count_room_bed          float64
count_room_dinning      float64
count_room_guest        float64
count_room_kitchen      float64
count_room_living       float64
count_room_maid         float64
count_room_storage      float64
count_room_utility      float64
date_created             object
date_updated             object
source                   object
url_unittype             object
dtype: object

Missing/Null Checking

In [225]:
opendata_unittype.isnull().any()

unittype_id             False
project_id              False
name_th                  True
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype             True
dtype: bool

In [226]:
opendata_unittype = opendata_unittype.dropna(subset=['price_min'])

In [227]:
opendata_unittype['name_th'] = opendata_unittype['name_th'].fillna('Unknown')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [228]:
opendata_unittype[['area_total_min_wa','area_usable_min','count_floor_internal']]  = opendata_unittype[['area_total_min_wa','area_usable_min','count_floor_internal']].fillna(1) 
# จำนวนห้อง, จำนวนลิฟต์, จำนวนแอร์
opendata_unittype[['count_airconditioner','count_elevator','count_parking','count_room_bath','count_room_bed','count_room_dinning','count_room_guest','count_room_kitchen','count_room_living','count_room_maid','count_room_storage','count_room_utility',]]  = opendata_unittype[['count_airconditioner','count_elevator','count_parking','count_room_bath','count_room_bed','count_room_dinning','count_room_guest','count_room_kitchen','count_room_living','count_room_maid','count_room_storage','count_room_utility',]].fillna(0)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [229]:
opendata_unittype.to_csv('opendata_unittype_C.csv', index=False)

##Data Clean train station

In [230]:
opendata_train_station.columns

Index(['row_number', 'gid', 'line_no', 'railway', 'line_typt', 'line_type',
       'status', 'line_th', 'line_en', 'station_th', 'station_en', 'latitude',
       'longitude', 'prov_namt', 'prov_name', 'amp_namt', 'amp_name',
       'tam_namt', 'tam_name', 'day'],
      dtype='object')

In [231]:
opendata_train_station = opendata_train_station[['gid', 'line_no', 'railway', 'line_typt', 'line_type',
       'status', 'line_th', 'line_en', 'station_th', 'station_en', 'latitude',
       'longitude', 'prov_namt', 'prov_name', 'amp_namt', 'amp_name',
       'tam_namt', 'tam_name', 'day']]
opendata_train_station

,gid,line_no,railway,line_typt,line_type,status,line_th,line_en,station_th,station_en,latitude,longitude,prov_namt,prov_name,amp_namt,amp_name,tam_namt,tam_name,day
0,254,9,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,อนาคต,สายสีเหลือง,Yellow Line,ศรีแบริ่ง,Si Bearing,13.644190,100.636665,สมุทรปราการ,SAMUT PRAKAN,บางพลี,BANG PHLI,บางแก้ว,BANG KAEO,30/9/2022
1,130,4,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีม่วง,Purple Line,ตลาดบางใหญ่,Talad Bang Yai,13.881849,100.409349,นนทบุรี,NONTHABURI,บางบัวทอง,BANG BUA THONG,บางรักพัฒนา,BANG RAK PHATTHANA,30/9/2022
2,110,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,บางแค,Bang Khae,13.711927,100.421581,กรุงเทพมหานคร,BANGKOK,บางแค,BANG KHAE,บางแค,BANG KHAE,30/9/2022
3,293,12,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสีเทา,Grey Line,ลาดพร้าว-87,Lat Phrao 87,13.801127,100.614995,กรุงเทพมหานคร,BANGKOK,บางกะปิ,BANG KAPI,คลองจั่น,KHLONG CHAN,30/9/2022
4,105,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,วัดมังกร,Wat Mangkon,13.741677,100.510687,กรุงเทพมหานคร,BANGKOK,สัมพันธวงศ์,SAMPHANTHAWONG,สัมพันธวงศ์,SAMPHANTHAWONG,30/9/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,286,11,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสีทอง,Gold line,สถานีคลองสาน,Khlong San,13.730545,100.507354,กรุงเทพมหานคร,BANGKOK,คลองสาน,KHLONG SAN,คลองสาน,KHLONG SAN,30/9/2022
314,99,3,รถไฟฟ้า,เอ็มอาร์ที,MRT,ปัจจุบัน,สายสีน้ำเงิน,Blue Line,สามย่าน,Sam Yan,13.732554,100.529493,กรุงเทพมหานคร,BANGKOK,ปทุมวัน,PATHUM WAN,วังใหม่,WANG MAI,30/9/2022
315,283,10,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,ปัจจุบัน,สายสีชมพู,Pink Line,ชลประทาน,Royal Irrigation Department,13.898695,100.507030,นนทบุรี,NONTHABURI,ปากเกร็ด,PAK KRET,บางตลาด,BANG TALAT,30/9/2022
316,252,9,รถไฟฟ้า,เอ็มอาร์ทีเอ,MRT,อนาคต,สายสีเหลือง,Yellow Line,ศรีเอี่ยม,Si Iam,13.664307,100.644072,กรุงเทพมหานคร,BANGKOK,บางนา,BANG NA,บางนาใต้,BANG NA TAI,30/9/2022
317,32,1,รถไฟฟ้า,บีทีเอส,BTS,ปัจจุบัน,สายสุขุมวิท,Sukhumvit Line,อโศก,Asok,13.737045,100.560344,กรุงเทพมหานคร,BANGKOK,คลองเตย,KHLONG TOEI,คลองเตย,KHLONG TOEI,30/9/2022

Missing/Null Checking

In [232]:
opendata_train_station.isnull().any()

gid           False
line_no       False
railway       False
line_typt     False
line_type     False
status        False
line_th       False
line_en       False
station_th    False
station_en    False
latitude      False
longitude     False
prov_namt     False
prov_name     False
amp_namt      False
amp_name      False
tam_namt      False
tam_name      False
day           False
dtype: bool

In [233]:
opendata_train_station.dtypes

gid             int64
line_no         int64
railway        object
line_typt      object
line_type      object
status         object
line_th        object
line_en        object
station_th     object
station_en     object
latitude      float64
longitude     float64
prov_namt      object
prov_name      object
amp_namt       object
amp_name       object
tam_namt       object
tam_name       object
day            object
dtype: object

In [234]:
opendata_train_station.to_csv('opendata_train_station_C.csv', index=False)

##รวมตาราง

In [235]:
import pandas as pd
opendata_project_C = pd.read_csv('opendata_project_C.csv')#หลัก
opendata_unittype_C = pd.read_csv('opendata_unittype_C.csv')
opendata_train_station_C = pd.read_csv('opendata_train_station_C.csv')

##1] รวมตาราง opendata_unittype_C เข้ากับ opendata_project_C

In [236]:
opendata_unittype_C.columns

Index(['unittype_id', 'project_id', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'area_total_min_wa',
       'area_usable_min', 'price_min', 'count_airconditioner',
       'count_elevator', 'count_floor_internal', 'count_parking',
       'count_room_bath', 'count_room_bed', 'count_room_dinning',
       'count_room_guest', 'count_room_kitchen', 'count_room_living',
       'count_room_maid', 'count_room_storage', 'count_room_utility',
       'date_created', 'date_updated', 'source', 'url_unittype'],
      dtype='object')

In [237]:
opendata_project_C.columns

Index(['project_id', 'name_en', 'name_th', 'propertytype_id',
       'propertytype_name_en', 'propertytype_name_th', 'price_min',
       'developer_id', 'developer_name_en', 'developer_name_th', 'latitude',
       'longitude', 'neighborhood_id', 'neighborhood_name_en',
       'neighborhood_name_th', 'subdistrict_id', 'subdistrict_name_en',
       'subdistrict_name_th', 'district_id', 'district_name_en',
       'district_name_th', 'province_id', 'province_name_en',
       'province_name_th', 'zipcode', 'count_elevator',
       'count_elevator_service', 'count_floor', 'count_parking', 'count_tower',
       'count_unit', 'count_unittype', 'facility_clubhouse',
       'facility_fitness', 'facility_meeting', 'facility_park',
       'facility_playground', 'facility_pool', 'facility_security',
       'date_created', 'date_finish', 'date_updated', 'source', 'url_project'],
      dtype='object')

In [239]:
opendata_project_C = opendata_project_C[['project_id', 'name_th',
       'propertytype_name_en','propertytype_name_th','price_min',]]
opendata_project_C.head(3)

,project_id,name_th,propertytype_name_en,propertytype_name_th,price_min
0,5ee08d64dda791001299b2a6,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,Detached House,บ้าน,3790000.0
1,project_11326,กิ๊ฟท์ คอนโดมิเนียม,Condo,คอนโด,1100000.0
2,62739c4089233e001362b001,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,Townhome,ทาวน์โฮม,0.0

In [241]:
#opendata_project_C.rename(columns={'price_min': 'price_min_p', 'propertytype_name_en': 'propertytype_name_en_P'}, inplace=True)
#opendata_project_C.head(3)

In [240]:
opendata_project_C

,project_id,name_th,propertytype_name_en,propertytype_name_th,price_min
0,5ee08d64dda791001299b2a6,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,Detached House,บ้าน,3790000.0
1,project_11326,กิ๊ฟท์ คอนโดมิเนียม,Condo,คอนโด,1100000.0
2,62739c4089233e001362b001,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,Townhome,ทาวน์โฮม,0.0
3,project_2010,บ้านแสนสบาย 1,Detached House,บ้าน,0.0
4,project_16838,บ้านพฤกษา ราชพฤกษ์-345,Townhome,ทาวน์โฮม,1930000.0
...,...,...,...,...,...
23273,project_12317,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,Townhome,ทาวน์โฮม,5700000.0
23274,project_12057,แอทโฮม เกษตร-นวมินทร์,Townhome,ทาวน์โฮม,3590000.0
23275,project_4461,ไอ-ดีไซน์ วงแหวน-รามอินทรา,Commercial,อาคารพาณิชย์,1870000.0
23276,project_144,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,Detached House,บ้าน,4000000.0
23277,project_16300,ทวีสุข การ์เด้นโฮม,Detached House,บ้าน,2800000.0

In [242]:
table_merge = opendata_unittype_C.merge(opendata_project_C, how ='left', left_on='project_id',right_on='project_id') 
print(table_merge.shape)

(44306, 30)

In [243]:
table_merge

,unittype_id,project_id,name_th_x,propertytype_id,propertytype_name_en_x,propertytype_name_th_x,area_total_min_wa,area_usable_min,price_min_x,count_airconditioner,...,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,name_th_y,propertytype_name_en_y,propertytype_name_th_y,price_min_y
0,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,1.0,37.3,2500000.0,0.0,...,0.0,0.0,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...,เฟ-ลิค คอนโด ลาดพร้าว-วังหิน 79,Condo,คอนโด,1390000.0
1,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,0.0,...,0.0,0.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,เซน บาย ศิวาลัย,Twin house,บ้านแฝด,1990000.0
2,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,0.0,...,0.0,0.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,เซน บาย ศิวาลัย,Detached House,บ้าน,1990000.0
3,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,0.0,...,0.0,0.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,เซน บาย ศิวาลัย,Townhome,ทาวน์โฮม,1990000.0
4,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,1.0,27.0,170000.0,0.0,...,0.0,0.0,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...,บ้านสวนชมน้ำ,Condo,คอนโด,170000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44301,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,1.0,353.0,23590000.0,0.0,...,1.0,0.0,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...,เศรษฐสิริ แจ้งวัฒนะ-ประชาชื่น 2,Detached House,บ้าน,15000000.0
44302,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,1.0,223.0,7490000.0,0.0,...,0.0,0.0,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...,คาซ่า วิลล์ ราชพฤกษ์-แจ้งวัฒนะ,Detached House,บ้าน,11500000.0
44303,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,1.0,180.0,3200000.0,0.0,...,0.0,0.0,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...,ณรงค์กิจ รามอินทรา,Detached House,บ้าน,3200000.0
44304,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,1.0,170.0,3790000.0,0.0,...,0.0,0.0,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...,วราสิริ รังสิต-ดอนเมือง,Townhome,ทาวน์โฮม,2490000.0
44305,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,1.0,170.0,3790000.0,0.0,...,0.0,0.0,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...,วราสิริ รังสิต-ดอนเมือง,Detached House,บ้าน,2490000.0